version: "3.7"

services:
    mysql:
        image: mysql:8.0
        container_name: 'mysql-desafio-conexa'
        labels:
            service_docker: desafio-conexa
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'desafio-conexa'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ../.docker/mysql/dbdata:/var/lib/mysql
        restart: always
